- pkg/vm/vm_linux.go
Prior to this, when a libvirt VM is manually shutdown, the domain persists but there was no way to reconnect to it. This will remove the existing VM and create a new one when an existing shutdown VM is found.
Fixes #30
> bug: Boot a shutdown libvirt VM via run

- cmd/run.go
- pkg/bootc/bootc_disk.go
The goal is to be able to trivially replicate locally a "cloud-like" scenario where:
- The rootfs is capped to some default size at disk image generation time
- The infrastructure provides a larger block device at boot time
> run: Add support for disk and rootfs controls

- pkg/bootc/bootc_disk.go
Chris noticed that the argument passing code didn't work, even though the end effect did work because we were injecting `--direct-io=off`.
> disk: Actually use losetup wrapper

- .github/workflows/ci.yml
- .gitignore
- Makefile
- test/e2e/e2e_test.go
- test/e2e/e2e_utils.go
- test/e2e/e2e_utils_darwin.go
- test/e2e/e2e_utils_linux.go
- test/e2e/test_vm.go
- test/resources/Containerfile.1
- test/resources/Containerfile.2
- test/resources/README.md
- test/resources/build.images.sh
This initial set of tests covers the basic use case of running and removing VMs/disk images.
> tests: Add e2e tests

- pkg/vm/vm.go
When running podman-bootc multiple times the known_hosts file quickly becomes cluttered with podman-bootc entries.
> ssh: Don't add an entry to known_hosts

- pkg/vm/vm_test.go
These tests are only testing linux VMs, so let's make sure this files only compiles on linux, so it will not interfere with future mac tests.
> Restrict VM test only on linux

- pkg/bootc/bootc_disk.go
Using the `Attach` API is *way* simpler than us forwarding output manually.
Set up a terminal by default, and together this fixes things like having bootc display an interactive spinner.
> disk: Simplify logging with attach API, use tty

- pkg/bootc/bootc_disk.go
This fixes a regression in the previous commit; the attachment takes over stdin and was competing with the ssh client.  We have no need for interactivity, so don't pass stdin.
While we're here, also set up cancellation for the attachment so that we know the operation is done when exiting the function, as we also want to transfer ownership of stdout/stderr back.
> disk: Don't pass stdin to install run, also set up cancellation

- README.md
Just a quick update of the README file.
Now you can install the latest code using `brew install --head podman-bootc`
> doc: Add new homebrew alternative download

- cmd/list.go
- cmd/rm.go
- cmd/root.go
- cmd/run.go
- cmd/ssh.go
- cmd/stop.go
- go.mod
- pkg/bootc/bootc_disk.go
- pkg/credentials/ssh.go
- pkg/user/user.go
- pkg/utils/podman.go
- pkg/vm/cloudinit.go
- pkg/vm/vm.go
- pkg/vm/vm_darwin.go
- pkg/vm/vm_linux.go
- pkg/vm/vm_test.go
- podman-bootc.go
- test/e2e/e2e_test.go
- test/e2e/e2e_utils.go
- test/e2e/e2e_utils_darwin.go
- test/e2e/e2e_utils_linux.go
Changes the old module name to the new location
> Update module name

- .packit.yaml
- rpm/packit.sh
- rpm/podman-bootc.spec
Adds a rpm spec file and packit configuration to trigger copr rpm builds on every merge request.
> Add packit initial support

- pkg/bootc/bootc_disk.go
It's only by doing this that we end up calling into the code inside `attach()` that tries to ensure the terminal size matching. Otherwise we just get the default of 80 columns (and no dynamic SIGWINCH resizing).
This fixes the output in https://github.com/containers/bootc/pull/655
> disk: Also pass stdin to install container

- cmd/run.go
- pkg/utils/podman.go
- pkg/vm/vm_linux.go
- podman-bootc.go
Removes unused code:
- load config while loading the domain
- unused waitgroup
Closes #53
> Remove dead code

- cmd/run.go
- pkg/bootc/bootc_disk.go
- pkg/utils/podman.go
- podman-bootc.go
Just a bit of code clean up and deduplication in preparation to support BIB
> Clean up and dedup code

- pkg/bootc/bootc_disk.go
This works around a goroutine leak in the `Attach` API. Honestly I think it's also just simpler for our use case here; we don't need the container ID for example because it's ephemeral, etc.
> disk: Switch to just invoking `podman run`

- cmd/images.go
Add a new `images` command that lists bootc-enabled images in the local store.
> podman-bootc images

- cmd/vmmon.go
- go.mod
- pkg/user/user.go
- pkg/utils/file.go
- pkg/utils/process.go
- pkg/vm/gvproxy.go
- pkg/vm/krunkit.go
- pkg/vm/monitor.go
- pkg/vm/oemstring.go
- pkg/vm/vm.go
- pkg/vm/vm_darwin.go
In order to switch from QEMU to krunkit we need to use gvproxy   to provide network support to the VM. We need to bound gvproxy     lifetime to krunkit lifetime, so there is not an "orphan"     daemon after krunkit finish.
We are using an "internal" command to monitor, in the future     this should be a different binary, but right now is the     easiest way. We save the pid of krunkit instead of the monitor    because the `stop` command sends a SIGINT to that pid, and    we currently are capturing the signal at podman-bootc.
> Macos switch to krunkit

- pkg/bootc/bootc_disk.go
Need a length check to avoid an out-of-bounds error.
> fix running an existing VM

- cmd/run.go
- pkg/credentials/ssh.go
- pkg/vm/vm.go
- pkg/vm/vm_darwin.go
- pkg/vm/vm_linux.go
- pkg/vm/vm_test.go
For simplicity, we were using the ssh key from podman-machine, but it has the inconvenience that this key is ed25519 and does not work in FIPS mode.
Let's generate and inject an RSA ssh key that it's FIPS approved.
This PR also removes `--no-creds` because it was broken, making the `run` and `ssh` command to fail. Since no-one complained we can safely remove it to avoid confuse the user. We can bring it back if someone ask for that functionality in the future.
Fixes #68
> Inject RSA ssh key

- README.md
- rpm/podman-bootc.spec
On Fedora we now need the `podman-machine` package which pulls in `virtiofsd`.
But also reorder and clean things up so that the MacOS/Fedora instructions are separate.
> README/spec: Clarify requirements

- pkg/bootc/bootc_disk.go
If the Containerfile has a USER directive, podman-run will execute the bootc command as that user, making the installation to fail. So, let's force the root as user/group to overwrite any possible USER directive.
> Overwrite the USER directive

- renovate.json
This removes the inheritance from platform-engineering-org/.github to fix the 'Edited' warning that prevents Renovate from automatically rebasing PRs.
The warning occurs because Renovate doesn't recognize bootc-bot as a valid commit author when it's configured through the inherited configuration.
See https://github.com/bootc-dev/infra/issues/19 for context.
This is part of a batch update across all bootc-dev repositories.
> renovate.json: Remove platform-engineering-org inheritance

- .github/workflows/ci.yml
For some amazing reason we have Perl being run in our CI apparently; this presumably broke at some point when the centos base image stopped including it?
> ci: Make linting job nonfatal
